export const WORD_POOL = [
    "Abandono", "Abismo", "Abrazo", "Absurdo", "Acariciar", "Acecho", "Acero", "Aclaparar", "Acompañar", "Acontecer", "Acorde", "Acoso", "Actitud", "Adiós", "Adivinar", "Admirar", "Admitir", "Adorar", "Adorno", "Adrenalina",
    "Afecto", "Aferrar", "Afilar", "Afinidad", "Aflicción", "Aflorar", "Agonía", "Agrio", "Agua", "Aguante", "Agudo", "Aguijón", "Aguja", "Ahogo", "Aire", "Aislar", "Ajeno", "Alarma", "Alba", "Albergar",
    "Alboroto", "Álbum", "Alcance", "Aldea", "Alegría", "Alento", "Alerta", "Alevosía", "Alfombra", "Alga", "Álgebra", "Algo", "Alguien", "Algún", "Alianza", "Aliciente", "Aliento", "Alivio", "Alma", "Almacén",
    "Almeja", "Almíbar", "Almirante", "Almohada", "Alpiste", "Alquiler", "Alrededor", "Altar", "Alterar", "Alternar", "Altitud", "Altura", "Alud", "Aludir", "Alumbrado", "Alumbrar", "Alumno", "Alusión", "Aluvión", "Alveolo",
    "Alzar", "Amable", "Amante", "Amar", "Amargo", "Amarillo", "Ámbar", "Ambición", "Ambiente", "Ámbito", "Ambos", "Amenaza", "Amén", "Amigo", "Amistad", "Amnistía", "Amo", "Amor", "Amortiguar", "Amparo",
    "Ampliar", "Amplio", "Amputar", "Amuleto", "Anales", "Análisis", "Ancla", "Anciano", "Ancho", "Ancla", "Andamio", "Andar", "Anécdota", "Anexo", "Ángel", "Angina", "Ángulo", "Angustia", "Anhelo", "Anidar",
    "Anillo", "Ánima", "Animal", "Aniversario", "Añadir", "Año", "Anoche", "Anómalo", "Anónimo", "Ansia", "Ansiedad", "Antaño", "Ante", "Antena", "Antes", "Anticipar", "Antifaz", "Antiguo", "Antojo", "Antorcha",
    "Anual", "Anudar", "Anular", "Anuncio", "Anzuelo", "Apagar", "Aparato", "Aparecer", "Apartar", "Apasión", "Apatía", "Apelar", "Apellido", "Apenas", "Apendice", "Aperitivo", "Apertura", "Apezar", "Ápice", "Apilar",
    "Apisonar", "Aplacar", "Aplastar", "Aplaudir", "Aplauso", "Aplicar", "Apocalipsis", "Apodo", "Apogeo", "Apolo", "Apostar", "Apoyo", "Apreciar", "Aprender", "Apremiar", "Apresar", "Apretar", "Aprisa", "Aprobar", "Apunte",
    "Aquel", "Aquí", "Arado", "Araña", "Arar", "Arbitrar", "Árbitro", "Árbol", "Arbusto", "Arca", "Arcada", "Arcano", "Arce", "Archivar", "Archivo", "Arco", "Arder", "Ardilla", "Ardor", "Área", "Arena",
    "Arenga", "Argolla", "Argón", "Argumento", "Aria", "Aridez", "Árido", "Aries", "Arista", "Arma", "Armada", "Armario", "Armar", "Armonía", "Aroma", "Arpa", "Arquero", "Arraigar", "Arrancar", "Arrasar",
    "Arrastrar", "Arrebat", "Arrecife", "Arreglo", "Arrepentir", "Arrestar", "Arriba", "Arribo", "Arriendo", "Arriesgar", "Arrimar", "Arrojo", "Arroma", "Arropar", "Arroyo", "Arroz", "Arruga", "Arruinar", "Arte", "Arteria",
    "Ártico", "Artífice", "Artilar", "Artista", "Asa", "Asado", "Asalto", "Asar", "Asbesto", "Ascenso", "Asco", "Ascua", "Asegurar", "Asentir", "Asepte", "Aserción", "Aserto", "Asfalto", "Asfixia", "Asilo",
    "Asimetría", "Asistir", "Asma", "Asno", "Asociar", "Asolar", "Asomar", "Asombro", "Aspecto", "Aspereza", "Áspero", "Aspirar", "Asquero", "Asta", "Aster", "Astilla", "Astral", "Astro", "Astuto", "Asumir",
    "Asunto", "Atajo", "Atar", "Atardecer", "Ataúd", "Ataviar", "Atención", "Atento", "Atenuar", "Aterrar", "Atisbo", "Atlas", "Atleta", "Atmósfera", "Átomo", "Atonía", "Atraer", "Atrás", "Atril", "Atrio",
    "Atroz", "Atuendo", "Atún", "Audaz", "Audio", "Auditor", "Aula", "Aullido", "Aumentar", "Aun", "Aunque", "Aura", "Aureo", "Auricular", "Aurora", "Ausencia", "Ausente", "Auspicio", "Auster", "Austro", "Auto",
    "Autor", "Aval", "Avanzar", "Avaro", "Ave", "Avellana", "Avena", "Avenida", "Aventura", "Avería", "Averso", "Avestruz", "Aviador", "Avión", "Aviso", "Avispa", "Avivar", "Axioma", "Ayer", "Ayuda", "Ayuno",
    "Azahar", "Azar", "Azogue", "Azote", "Azúcar", "Azul", "Babor", "Bacalao", "Bacilo", "Bachiller", "Bacio", "Báculo", "Bagaje", "Bahía", "Bailar", "Baile", "Baja", "Bajar", "Bajo", "Bala", "Balance",
    "Balaustre", "Balcón", "Baldío", "Baldosa", "Ballena", "Ballet", "Balón", "Balsa", "Bálsamo", "Baluarte", "Bambú", "Banana", "Banca", "Banco", "Banda", "Bandejar", "Bandera", "Bando", "Banquete", "Baño", "Baraja",
    "Baratija", "Barba", "Barbarie", "Barca", "Barco", "Bardo", "Bario", "Barniz", "Barón", "Barra", "Barranco", "Barre", "Barrera", "Barril", "Barro", "Bártulo", "Barullo", "Basa", "Basar", "Base", "Básico",
    "Basilica", "Bastan", "Bastón", "Basura", "Bata", "Batalla", "Batería", "Batida", "Batuta", "Baúl", "Bautizo", "Baya", "Bebé", "Beber", "Bebida", "Beca", "Becerro", "Bedel", "Beisbol", "Bejuco", "Belén",
    "Belga", "Bélico", "Belleza", "Bello", "Bellota", "Bemol", "Bendito", "Bengala", "Bermejo", "Beso", "Bestia", "Betún", "Bicho", "Biela", "Bien", "Bienal", "Biombo", "Boda", "Bofetada", "Boga", "Bohemio",
    "Bola", "Boleta", "Bolígrafo", "Bólido", "Bolso", "Bomba", "Bondad", "Bonito", "Borde", "Bordo", "Boreal", "Borla", "Borne", "Borra", "Borrar", "Bosque", "Bota", "Botella", "Botín", "Botón", "Bóveda",
    "Boyante", "Bozal", "Bracear", "Braga", "Bramar", "Brava", "Brazo", "Brecha", "Breve", "Brillo", "Brincar", "Brindis", "Brío", "Brisa", "Broca", "Broma", "Bronce", "Brotar", "Brote", "Bruja", "Brújula",
    "Bruma", "Brusco", "Brutal", "Bruto", "Buque", "Burbuja", "Burla", "Busca", "Búsqueda", "Butaca", "Buzón", "Cábala", "Cabaña", "Cabella", "Cabello", "Cabeza", "Cabina", "Cable", "Cabo", "Caballo", "Cabrío",
    "Cacao", "Cacho", "Cada", "Cadena", "Cadera", "Cadete", "Cadiz", "Cadmio", "Caducar", "Caer", "Café", "Caída", "Caja", "Cajón", "Cal", "Calabozo", "Calado", "Calamar", "Calambre", "Caland", "Calavera",
    "Calcar", "Calced", "Calcio", "Caldera", "Caldo", "Calend", "Calibre", "Cálice", "Cálido", "Caliente", "Califica", "Caligo", "Cáliz", "Callar", "Calle", "Calleja", "Callos", "Calma", "Calor", "Calumnia", "Calvario",
    "Calvo", "Calza", "Calzada", "Cama", "Cámara", "Camastro", "Cámbium", "Cambio", "Camilla", "Caminar", "Camino", "Camión", "Camisa", "Campana", "Campaña", "Campeón", "Campus", "Can", "Canal", "Canario", "Canasta",
    "Canavis", "Cancel", "Cáncer", "Canción", "Candado", "Candela", "Cándido", "Canela", "Caney", "Cangrejo", "Canica", "Canilla", "Canino", "Canje", "Cano", "Canoa", "Canon", "Cansar", "Cantar", "Cántico", "Cantina",
    "Capa", "Capar", "Capaz", "Capilla", "Capital", "Capitán", "Cápitulo", "Capsula", "Captar", "Captura", "Cara", "Caracola", "Carácter", "Carajo", "Caramba", "Caravana", "Carbón", "Carca", "Carcasa", "Cárcel", "Cardo",
    "Carga", "Cariño", "Carne", "Carné", "Carolina", "Carpeta", "Carrera", "Carro", "Carta", "Cartel", "Cartera", "Cartón", "Casa", "Casada", "Cáscara", "Casco", "Caserío", "Casi", "Casilla", "Casino",
    "Caso", "Casta", "Castillo", "Castigo", "Castro", "Casual", "Cata", "Catálogo", "Catarro", "Catástrofe", "Cauce", "Caucho", "Causa", "Cautivo", "Cava", "Caverna", "Caza", "Cazar", "Cebolla", "Cebú",
    "Cebra", "Cedar", "Cedro", "Cegar", "Cejas", "Celaje", "Celda", "Celebrar", "Celes", "Celia", "Celo", "Celos", "Célula", "Cement", "Cena", "Ceniza", "Censo", "Censor", "Centavo", "Central", "Centro",
    "Cepillo", "Cera", "Cerca", "Cerco", "Cerda", "Cerdo", "Cereal", "Cerebro", "Cereza", "Cerilla", "Cero", "Cerrar", "Cerro", "Certeza", "Certificar", "Cerveza", "Césped", "Cesta", "Cetro", "Chacal", "Chapa",
    "Chaqueta", "Charco", "Charla", "Chasis", "Chica", "Chico", "Chicle", "Chile", "Chimenea", "Chisme", "Chispa", "Chiste", "Choque", "Chorro", "Choza", "Chulo", "Chupete", "Cian", "Ciclo", "Ciclón", "Ciego",
    "Cielo", "Ciencia", "Cien", "Cierre", "Cifra", "Cigala", "Cigarrillo", "Cima", "Cinc", "Cincel", "Cinco", "Cine", "Cinta", "Cintura", "Círculo", "Cirio", "Cisne", "Cisterna", "Cit", "Cita", "Ciudad",
    "Cívico", "Civil", "Clamor", "Clan", "Clara", "Claro", "Clase", "Clave", "Clavel", "Clavo", "Clich", "Cliente", "Clima", "Clínica", "Cloro", "Club", "Cobalto", "Cobrar", "Cobre", "Cocina", "Coco",
    "Coche", "Codicia", "Código", "Codo", "Cofre", "Cohete", "Cola", "Colar", "Colchón", "Colegio", "Cólera", "Colina", "Collar", "Colmo", "Color", "Columna", "Coma", "Comer", "Cometa", "Cómico", "Comida",
    "Comienzo", "Comité", "Como", "Cómoda", "Compra", "Común", "Con", "Concha", "Conde", "Conejo", "Confiar", "Confort", "Cónico", "Cono", "Contar", "Contra", "Control", "Copa", "Copia", "Copol",
    "Coral", "Coraza", "Corazón", "Cordado", "Cordel", "Cordero", "Cordón", "Coro", "Corona", "Corral", "Correa", "Correo", "Correr", "Corrosión", "Cortar", "Corte", "Cortina", "Corto", "Cosa", "Cosecha",
    "Cosmos", "Costa", "Coste", "Costilla", "Costumbre", "Cota", "Cotejar", "Coto", "Cráneo", "Cráter", "Crear", "Crece", "Creer", "Crema", "Cresta", "Cría", "Criar", "Criba", "Crimen", "Crisis", "Cristal",
    "Crítica", "Cromo", "Crónica", "Cruce", "Crudo", "Cruel", "Cruz", "Cuadro", "Cuanto", "Cuarzo", "Cuatro", "Cuba", "Cubo", "Cucaracha", "Cuchillo", "Cuello", "Cuenca", "Cuerda", "Cuerno", "Cuerpo", "Cuesta",
    "Cueva", "Cuidado", "Culpa", "Culto", "Cuna", "Cuota", "Cúpula", "Cura", "Curar", "Curva", "Cúspide", "Cutis", "Dada", "Dador", "Daga", "Dalia", "Dama", "Danza", "Daño", "Dar", "Dardo",
    "Datación", "Dátil", "Dato", "Deber", "Débil", "Década", "Decano", "Decir", "Dedo", "Defecto", "Defensa", "Dejar", "Delfín", "Delgado", "Delito", "Delta", "Demanda", "Demasiado", "Demonio", "Densidad", "Dentro",
    "Depósito", "Derecho", "Deriva", "Derrame", "Derrota", "Desayuno", "Descanso", "Desdén", "Deseo", "Desfile", "Desierto", "Desnudo", "Despacho", "Después", "Destino", "Detalle", "Deuda", "Día", "Diabetes", "Diablo", "Dial",
    "Diálogo", "Diamante", "Diario", "Dibujo", "Diccionario", "Dicha", "Diente", "Dieta", "Diez", "Difícil", "Digno", "Dilema", "Diluvio", "Dimensión", "Dinero", "Dios", "Diploma", "Dique", "Directo", "Disco",
    "Discurso", "Diseño", "Distancia", "Doble", "Doce", "Doctor", "Doctrina", "Documento", "Dólar", "Dolor", "Domador", "Domingo", "Dominio", "Donar", "Donde", "Dorado", "Dormir", "Dorso", "Dos", "Dosis",
    "Dote", "Draga", "Drama", "Droga", "Duende", "Dueño", "Dulce", "Duna", "Dúo", "Duque", "Dureza", "Duro", "Ebanista", "Ebano", "Ecléctico", "Eclipse", "Eco", "Economía", "Ecuación", "Edad", "Edén",
    "Edición", "Edificio", "Efecto", "Eficaz", "Ego", "Eje", "Ejemplo", "Ejercicio", "Ejército", "Elastico", "Elección", "Electro", "Elegante", "Elegir", "Elemento", "Elefante", "Elegía", "Elevado", "Eliminar", "Elipse",
    "Elite", "Elogio", "Ella", "Ellos", "Emanar", "Embajada", "Emblema", "Embolia", "Embudo", "Embuste", "Emoción", "Empacar", "Empate", "Empeño", "Empezar", "Empleo", "Empresa", "Empuje", "Enano", "Encanto",
    "Encaje", "Enchufe", "Encía", "Encima", "Encuesta", "Energetico", "Energía", "Enero", "Enfado", "Enfermo", "Enfoque", "Enigma", "Enlace", "Enojo", "Enorme", "Ensayo", "Enseñar", "Ensueño", "Entrada", "Entrar",
    "Entre", "Entrega", "Entuerto", "Envase", "Envidia", "Envío", "Enzima", "Epígrafe", "Episodio", "Época", "Equilibrio", "Equipo", "Equivoco", "Eras", "Erección", "Ergio", "Erial", "Eros", "Erosión", "Error",
    "Erudito", "Erupción", "Escala", "Escándalo", "Escapar", "Escasez", "Escena", "Esclavo", "Escoba", "Escoger", "Escuela", "Escribir", "Escuchar", "Escudo", "Esculpir", "Escupir", "Esencia", "Esfera", "Esfuerzo",
    "Esgrimista", "Esmalte", "Esmeralda", "Esmero", "Espacio", "Espada", "Espalda", "España", "Espanto", "Español", "Espejo", "Espera", "Especia", "Especie", "Espectro", "Espejo", "Esperanza", "Espesa", "Espesor", "Espía",
    "Espina", "Espiral", "Espíritu", "Esplendor", "Esponja", "Esposa", "Esposo", "Espuela", "Espuma", "Esquema", "Esquí", "Esquina", "Establos", "Estaca", "Estado", "Estafa", "Estallar", "Estambre", "Estancia", "Estanque",
    "Estante", "Estaque", "Estar", "Estatua", "Este", "Estela", "Estepa", "Estera", "Estético", "Estilo", "Estima", "Estirar", "Estío", "Esto", "Estoque", "Estrella", "Estreno", "Estrés", "Estribo", "Estrofa",
    "Estructura", "Estuche", "Estudio", "Etapa", "Eter", "Eterno", "Etica", "Etiqueta", "Evacuar", "Evadir", "Evaluar", "Evidencia", "Evitar", "Evocar", "Exacto", "Examen", "Excavar", "Exceder", "Excelencia", "Exceso",
    "Excitación", "Excluir", "Excursión", "Excusa", "Exento", "Exhibir", "Exilio", "Existir", "Existo", "Éxito", "Éxodo", "Exotico", "Exótico", "Expansión", "Expedir", "Experto", "Explicar", "Explorar", "Explosión", "Exponer",
    "Expreso", "Expulsar", "Exquisito", "Extasis", "Extender", "Externo", "Extinto", "Extra", "Extraño", "Extremo", "Fábula", "Fachada", "Fácil", "Factura", "Facultad", "Faena", "Fagot", "Faisán", "Faja", "Falange",
    "Falda", "Falla", "Fallo", "Falso", "Falta", "Fama", "Familia", "Fanal", "Fangal", "Fango", "Fantasía", "Fantasma", "Farallón", "Farándula", "Fardo", "Fariseo", "Farmacia", "Farol", "Faro", "Farsa",
    "Fase", "Fastidio", "Fatal", "Fatiga", "Fatuo", "Fauces", "Fauna", "Favor", "Fax", "Feb", "Febrero", "Fecha", "Felicidad", "Felino", "Feliz", "Felpa", "Femenino", "Fémur", "Fenómeno", "Feo",
    "Feraz", "Feria", "Fermento", "Feroz", "Féretro", "Fibra", "Ficha", "Fid", "Fiel", "Fiebre", "Fiesta", "Figura", "Fijar", "Fila", "Filial", "Filo", "Filtrar", "Fin", "Final", "Finca",
    "Fineza", "Fingir", "Fino", "Firma", "Firme", "Fiscal", "Física", "Fisura", "Flaco", "Flagelo", "Flamenco", "Flanco", "Flato", "Flauta", "Flecha", "Fleco", "Fleje", "Flema", "Flete", "Flor",
    "Flota", "Fluctuar", "Fluido", "Flujo", "Flúor", "Fobia", "Foca", "Foco", "Fogonero", "Follaje", "Fomento", "Fondo", "Fonil", "Fono", "Forjar", "Forma", "Forro", "Fortaleza", "Fortuna", "Forzar",
    "Fosa", "Fósforo", "Fórmula", "Foto", "Fracción", "Frágil", "Fragmento", "Fragor", "Franja", "Frase", "Fraude", "Frecuente", "Frenar", "Freno", "Frente", "Fresa", "Fresco", "Frida", "Frío", "Frisa",
    "Frito", "Frontal", "Frontera", "Frote", "Fruto", "Fuego", "Fuente", "Fuera", "Fuerte", "Fuga", "Fugar", "Fugaz", "Fulgor", "Fumar", "Funda", "Fundir", "Furia", "Furor", "Fusi", "Fútbol",
    "Futuro", "Gabinete", "Gacela", "Gafas", "Gaita", "Gajo", "Gala", "Galán", "Galaxia", "Galera", "Galería", "Galgada", "Galgo", "Galion", "Gallina", "Gallo", "Gallón", "Gama", "Gamba", "Ganado",
    "Ganancia", "Ganar", "Gancho", "Ganga", "Ganso", "Gante", "Garaje", "Garante", "Garbo", "Garfio", "Garganta", "Garita", "Garra", "Garrafa", "Garrote", "Garza", "Gas", "Gasa", "Gasto", "Gata",
    "Gato", "Gatillo", "Gaviota", "Gaza", "Gema", "Gemelo", "Gemido", "Gemir", "General", "Género", "Genio", "Gente", "Genuino", "Geometría", "Geranio", "Gerente", "Gesto", "Gimnasia", "Ginebra", "Girasol",
    "Giro", "Glacial", "Gladiator", "Glándula", "Globo", "Gloria", "Glosa", "Glúteo", "Gnomo", "Gobernar", "Goce", "Gofre", "Gol", "Golf", "Golgota", "Goloso", "Golpe", "Goma", "Góndola", "Gordo",
    "Gorgora", "Gorila", "Gorro", "Gota", "Goteo", "Gozar", "Gozne", "Gozo", "Grabado", "Grabar", "Gracia", "Grácil", "Grada", "Grado", "Gráfico", "Grafito", "Grano", "Granja", "Granizo", "Granuja",
    "Grapa", "Grasa", "Graso", "Gratis", "Gratitud", "Grato", "Grau", "Gravamen", "Grave", "Grecia", "Gremio", "Greña", "Grieta", "Grifo", "Grillo", "Grima", "Gringo", "Gris", "Grito", "Grosor",
    "Grúa", "Gruesa", "Grueso", "Grumo", "Gruñir", "Grupo", "Gruta", "Guante", "Guapo", "Guare", "Guardar", "Guarida", "Guerra", "Guía", "Guijarro", "Guion", "Guiño", "Guitarra", "Gula", "Gusto",
    "Habanero", "Haber", "Hábil", "Hábito", "Habla", "Hablar", "Hacer", "Hacia", "Hada", "Halo", "Hambre", "Harina", "Hartar", "Harto", "Hasta", "Hato", "Hazaña", "Hebilla", "Hebra", "Hecho",
    "Hechizo", "Hectarea", "Hedor", "Helado", "Helar", "Hélice", "Helecho", "Helio", "Hembra", "Henchir", "Heno", "Heñir", "Herencia", "Herida", "Herir", "Hermano", "Hermoso", "Héroe", "Hervir", "Hielo",
    "Hierba", "Hierro", "Higado", "Higo", "Hija", "Hijo", "Hilo", "Himno", "Hincapié", "Hincar", "Hinchado", "Hip hop", "Hipo", "Hispano", "Historia", "Hito", "Hocico", "Hogar", "Hoja", "Hola",
    "Holgado", "Hollejo", "Hollín", "Hombre", "Hombro", "Homenaje", "Homicida", "Hondo", "Hondura", "Honesto", "Hongo", "Honor", "Honra", "Hora", "Horadar", "Horca", "Horizonte", "Hormiga", "Horno",
    "Horquilla", "Horror", "Hortensia", "Hospital", "Hostigar", "Hostil", "Hoy", "Hoyo", "Hueco", "Huelga", "Huella", "Huerto", "Hueso", "Huésped", "Huevo", "Huida", "Huir", "Humano", "Húmedo", "Humilde",
    "Humo", "Humor", "Hundir", "Huracán", "Hurto", "Husmear", "Huso", "Ibar", "Icono", "Ida", "Edad", "Idea", "Ideal", "Idear", "Idem", "Idéntico", "Idilio", "Idioma", "Idiota", "Idolo",
    "Iglesia", "Ignoto", "Igual", "Ijada", "Ilegal", "Ileso", "Ilusión", "Ilustre", "Imán", "Imagen", "Imitar", "Impar", "Ímpetu", "Implorar", "Importar", "Imponer", "Improviso", "Impulso", "Inane", "Inca",
    "Incapaz", "Incendio", "Incierto", "Inciso", "Incluso", "Incurrir", "Indagar", "Indicar", "Índice", "Indio", "Individuo", "Índole", "Inducir", "Indulto", "Inercia", "Inerto", "Inexacto", "Infausto", "Infierno", "Ínfimo",
    "Inflar", "Informe", "Ingenio", "Ingle", "Ingrato", "Ingreso", "Inhalar", "Inhibir", "Inhóspito", "Inicuo", "Inicio", "Inmune", "Innato", "Inocente", "Inquieto", "Inscrito", "Insigne", "Insólito", "Insulto", "Intacto",
    "Intentar", "Interés", "Interior", "Íntimo", "Intriga", "Intuso", "Inundar", "Invadir", "Invasión", "Inventar", "Invernal", "Invierno", "Involucrar", "Ión", "Ira", "Iris", "Irreal", "Irse", "Isla", "Islote",
    "Istmo", "Ítem", "Iterar", "Izquierda", "Jabalí", "Jabón", "Jacinto", "Jactancia", "Jade", "Jae", "Jaguar", "Jaime", "Jalea", "Jalón", "Jamás", "Jamón", "Jaque", "Jarabe", "Jardín", "Jaro",
    "Jarra", "Jaula", "Jazmín", "Jefe", "Jenjibre", "Jerga", "Jersey", "Jeta", "Jiba", "Jicot", "Jinete", "Jirafa", "Jirón", "Jocoso", "Jornada", "Joroba", "Joven", "Joya", "Juan", "Jubileo",
    "Júbilo", "Judío", "Juego", "Juerga", "Jueves", "Juez", "Jugada", "Jugador", "Jugar", "Jugo", "Juguete", "Juicio", "Julio", "Junco", "Junio", "Junta", "Junto", "Jurado", "Jurar", "Justo",
    "Juvenil", "Juzgar", "Kilo", "Labor", "Labrar", "Laca", "Lacre", "Ladear", "Lado", "Ladrillo", "Ladrar", "Lago", "Lágrima", "Laguna", "Laico", "Lama", "Lampar", "Lana", "Lance", "Lancha",
    "Lancero", "Lánguido", "Lanudo", "Lanza", "Lapidó", "Lápiz", "Lapso", "Largo", "Larva", "Lasca", "Láser", "Lástima", "Lastre", "Latente", "Latido", "Latón", "Latitud", "Laúd", "Laurel", "Lava",
    "Lavar", "Lazo", "Leal", "Lección", "Lecho", "Lector", "Leer", "Legado", "Lejano", "Lejos", "Lema", "Lengua", "Lento", "Leña", "León", "Leopardo", "Lepra", "Lerdo", "Lesión", "Leticia",
    "Letra", "Leudar", "Levante", "Levt", "Ley", "Leyenda", "Liar", "Libación", "Líbano", "Libelo", "Liberal", "Libertad", "Libra", "Libre", "Libro", "Licencia", "Liceo", "Lícito", "Licor", "Lidia",
    "Liebre", "Lienzo", "Liga", "Ligar", "Ligero", "Lila", "Lili", "Lima", "Limar", "Limbo", "Límite", "Limón", "Limosna", "Limpio", "Lindar", "Linde", "Lindo", "Línea", "Linfa", "Lino",
    "Linterna", "Lío", "Líquido", "Lirio", "Lisa", "Liso", "Lista", "Listo", "Literal", "Litio", "Liue", "Llama", "Llamar", "Llano", "Llanura", "Llave", "Llegar", "Llenar", "Lleno", "Llevar",
    "Llorar", "Lloro", "Llover", "Lluvia", "Lobo", "Local", "Loco", "Locura", "Lodo", "Lograr", "Logro", "Loma", "Lomo", "Longevidad", "Lona", "Losa", "Lote", "Lucha", "Luchar", "Lúcido",
    "Lucero", "Luces", "Lucha", "Lucir", "Lodo", "Luege", "Lugar", "Lujo", "Lumbrera", "Luna", "Lunar", "Lunes", "Lupa", "Lustre", "Luto", "Luz", "Macizo", "Madera", "Madre", "Madriguera",
    "Maestro", "Magia", "Magma", "Mago", "Maíz", "Mal", "Malicia", "Malla", "Malo", "Malva", "Manada", "Mancha", "Mandar", "Mando", "Manejar", "Manga", "Manía", "Mano", "Mansión", "Manso",
    "Manta", "Manto", "Manzana", "Mapa", "Máquina", "Mar", "Maravilla", "Marca", "Marcar", "Marco", "Marea", "Marfil", "Margen", "Marina", "Mármol", "Martes", "Martillo", "Marzo", "Más", "Masa",
    "Máscara", "Mástil", "Matar", "Matiz", "Mazo", "Meandro", "Medalla", "Media", "Médico", "Medida", "Medio", "Mejilla", "Mejor", "Melancolía", "Melena", "Melon", "Memoria", "Mencionar", "Menor", "Mente",
    "Menú", "Mercado", "Meridiano", "Mes", "Mesa", "Meta", "Metáfora", "Metal", "Método", "Metro", "Mezcla", "Miedo", "Miel", "Miércoles", "Mierda", "Mil", "Milagro", "Militar", "Milla", "Mimar",
    "Mimbre", "Mina", "Mineral", "Mínimo", "Minuto", "Mirada", "Mirar", "Misa", "Misión", "Misterio", "Mito", "Mitad", "Mixto", "Moda", "Modelo", "Moderno", "Modo", "Mofeta", "Molde", "Moler",
    "Molino", "Momento", "Monarca", "Moneda", "Monitor", "Mono", "Monstruo", "Montaña", "Montar", "Monte", "Mordaz", "Morder", "Moreno", "Morir", "Moro", "Mortaja", "Mosca", "Motín", "Moto", "Motor",
    "Móvil", "Mozo", "Mucho", "Mudar", "Mudo", "Mueble", "Mueca", "Muela", "Muelle", "Muerte", "Muerto", "Muestra", "Mugre", "Mujer", "Mulo", "Multa", "Mundo", "Muñeca", "Muralla", "Muro",
    "Musa", "Músculo", "Museo", "Música", "Muslo", "Mutar", "Mutilar", "Mutuo", "Nácar", "Nacer", "Nación", "Nada", "Nadar", "Nadie", "Nafta", "Naipe", "Naranja", "Nariz", "Narrar", "Nata",
    "Nativo", "Naturaleza", "Nave", "Navío", "Neblina", "Necio", "Néctar", "Negar", "Negro", "Neón", "Nervio", "Neto", "Nevada", "Ni", "Nicho", "Niebla", "Nieto", "Nieve", "Nimbo", "Nina",
    "Nivel", "No", "Noble", "Noche", "Nómada", "Nombre", "Norma", "Norte", "Nos", "Nota", "Notar", "Noval", "Nube", "Nuca", "Nudo", "Nuera", "Nueva", "Nueve", "Nuevo", "Nulo",
    "Número", "Nunca", "Nutria", "Ñandú", "Ñame", "Obeso", "Objeto", "Obra", "Obsesión", "Obvio", "Ocaso", "Océano", "Ocho", "Ocio", "Ocre", "Octavo", "Ocular", "Ocultar", "Ocupar", "Ocurrir",
    "Oda", "Odio", "Oeste", "Ofensa", "Oferta", "Oficio", "Oír", "Ojal", "Ojo", "Ola", "Oler", "Olfato", "Olmo", "Olor", "Olvido", "Ombligo", "Omega", "Omisión", "Omitir", "Once",
    "Onde", "Ónix", "Opaco", "Ópalo", "Opción", "Ópera", "Opinión", "Opio", "Opuesto", "Ora", "Oráculo", "Oral", "Orange", "Órbita", "Orden", "Oreja", "Organismo", "Orgullo", "Oriente", "Origen",
    "Orilla", "Oro", "Orquestar", "Orto", "Oruga", "Ósculo", "Oscuro", "Oso", "Ostentar", "Ostras", "Otoño", "Otro", "Oval", "Oveja", "Óvulo", "Oxígeno", "Oyente", "Ozono", "Pabellón", "Pacer",
    "Paciencia", "Pacto", "Padre", "Pagar", "Página", "País", "Paisaje", "Paja", "Pájaro", "Pala", "Palabra", "Palacio", "Paladar", "Palanca", "Pálido", "Palma", "Palmo", "Palo", "Paloma", "Palpitar",
    "Pan", "Panal", "Pañal", "Pánico", "Paño", "Pantano", "Panteón", "Papá", "Papel", "Par", "Para", "Parada", "Paraíso", "Pardo", "Pared", "Pareja", "Paro", "Parque", "Párpado", "Parte",
    "Partir", "Pasar", "Pascua", "Paseo", "Pasión", "Paso", "Pasta", "Pata", "Patio", "Pausa", "Paz", "Peaje", "Pecho", "Pedal", "Pedir", "Pegar", "Pecado", "Peinar", "Pelar", "Pelea",
    "Película", "Peligro", "Pelo", "Pelota", "Peluche", "Pena", "Péndulo", "Penuria", "Peña", "Peón", "Peor", "Pepino", "Pera", "Pera", "Percibir", "Percha", "Perder", "Perdón", "Perea", "Pereza",
    "Perfil", "Perfume", "Perla", "Perro", "Persa", "Pesa", "Pesado", "Pesar", "Pesca", "Peste", "Pétalo", "Pez", "Piano", "Picar", "Pico", "Pie", "Piedra", "Piel", "Pierna", "Pieza",
    "Pila", "Pilar", "Píldora", "Pilón", "Pilote", "Pincel", "Pingüino", "Pino", "Pintar", "Pinza", "Pipa", "Pirámide", "Pirata", "Piso", "Pista", "Pistón", "Pivote", "Pixel", "Pizarra", "Placa",
    "Placer", "Plaga", "Plan", "Plano", "Planta", "Plata", "Plato", "Playa", "Plaza", "Plazo", "Pleito", "Pleno", "Pliego", "Plomo", "Pluma", "Plus", "Pobre", "Poco", "Poder", "Poema",
    "Poesía", "Poeta", "Polar", "Polea", "Polen", "Polvo", "Pomada", "Pomo", "Pompa", "Poner", "Puente", "Popa", "Por", "Porque", "Portar", "Poste", "Potro", "Pozo", "Prado", "Precioso",
    "Precio", "Premio", "Prensa", "Presa", "Presencia", "Preso", "Prestar", "Prima", "Primo", "Prisa", "Prisma", "Proa", "Probar", "Proceso", "Producto", "Profundo", "Promesa", "Pronto", "Propio", "Prosa",
    "Prueba", "Pueblo", "Puente", "Puerta", "Puerto", "Puesto", "Pugna", "Pulgar", "Pulir", "Pulmón", "Pulpa", "Pulso", "Puma", "Punta", "Punto", "Puñal", "Puño", "Puro", "Púrpura", "Que",
    "Quedar", "Queja", "Quemura", "Querer", "Queso", "Quien", "Quietud", "Quinto", "Quitar", "Quizá", "Rábano", "Racha", "Rada", "Radar", "Radio", "Radium", "Radón", "Rafa", "Ráfaga", "Raíz",
    "Raja", "Rama", "Ramal", "Rampa", "Rana", "Rango", "Rápido", "Raptar", "Raro", "Rasa", "Rasgar", "Rasgo", "Rastro", "Rata", "Rato", "Rayo", "Razon", "Real", "Rebaño", "Rebelde",
    "Recibo", "Recio", "Recreo", "Red", "Redil", "Reflejo", "Refugio", "Regalar", "Regalo", "Regaño", "Regar", "Regir", "Regla", "Reina", "Reino", "Reír", "Reja", "Relato", "Relieve", "Reloj",
    "Remar", "Remite", "Reno", "Renta", "Reparar", "Reposo", "Res", "Resaca", "Residuo", "Resina", "Respeto", "Restar", "Resto", "Reto", "Retorno", "Reunir", "Reverso", "Reves", "Revista", "Rey",
    "Rezar", "Ría", "Ribera", "Rico", "Riego", "Riel", "Riesgo", "Rifa", "Rigidez", "Rígido", "Rigor", "Ril", "Rima", "Rincón", "Río", "Riqueza", "Risa", "Ritmo", "Rito", "Rival",
    "Robar", "Roble", "Robo", "Roca", "Roce", "Rocío", "Rodar", "Rodilla", "Rodio", "Roedor", "Rojo", "Rol", "Rollo", "Roma", "Romance", "Romero", "Romper", "Ron", "Ronda", "Ronronear",
    "Ropa", "Rosa", "Rosario", "Rosca", "Roso", "Roto", "Rótulo", "Rozar", "Rubí", "Rubio", "Rueda", "Ruego", "Rugir", "Ruido", "Ruina", "Rulo", "Rumbo", "Rumor", "Ruta", "Saber",
    "Sabio", "Sabor", "Sable", "Sacar", "Saco", "Sacro", "Saeta", "Sal", "Sala", "Saldo", "Salir", "Salitre", "Salmo", "Salón", "Salsa", "Saltar", "Salto", "Salud", "Salva", "Salvaje",
    "Sanar", "Sandalia", "Sangre", "Santo", "Sapo", "Saque", "Sara", "Sari", "Sarna", "Sartén", "Sastre", "Satén", "Saturno", "Sauce", "Sauna", "Savia", "Sazón", "Se", "Sebo", "Secar",
    "Sección", "Seco", "Secreto", "Seda", "Sede", "Sedento", "Segar", "Seguir", "Segundo", "Seguro", "Seis", "Sello", "Selva", "Semana", "Semilla", "Senda", "Senil", "Seno", "Señal", "Señar",
    "Señor", "Seno", "Sentir", "Seña", "Separar", "Sepia", "Sequía", "Sera", "Sereno", "Serie", "Serio", "Serpiente", "Servir", "Sésamo", "Sesgo", "Sesion", "Sete", "Seudo", "Sexto", "Si",
    "Sidra", "Siego", "Siete", "Siesta", "Sifón", "Sigilo", "Siglo", "Signo", "Sílaba", "Silbar", "Silencio", "Silla", "Sillón", "Símbolo", "Simio", "Simple", "Sin", "Sincero", "Sindicato", "Sinfin",
    "Sino", "Sintonía", "Siquiera", "Sirena", "Sirio", "Sirviente", "Siseo", "Sistema", "Sitio", "Situar", "Sobra", "Sobre", "Socio", "Soda", "Sofá", "Soga", "Sol", "Solar", "Soler", "Sólido",
    "Solo", "Soltar", "Sombra", "Someter", "Somos", "Son", "Soñar", "Sonido", "Sonoro", "Sonrisa", "Sopa", "Soplar", "Soplo", "Soporte", "Sordo", "Sorpresa", "Sortear", "Sosegar", "Soslayo", "Sospecha",
    "Sostén", "Sótano", "Soto", "Suave", "Subida", "Subir", "Súbito", "Subyacer", "Succión", "Sucio", "Sudor", "Sueño", "Suero", "Suerte", "Sufijo", "Suficiente", "Sufrir", "Sugerir", "Suizo", "Sujetar",
    "Sujeto", "Suma", "Sumar", "Sumir", "Súper", "Suponer", "Suprimir", "Sur", "Surco", "Surgir", "Surtidor", "Susurro", "Sutil", "Suyo", "Tabaco", "Tabla", "Tabique", "Tablero", "Tabú", "Tacaño",
    "Tacha", "Taciturno", "Tacle", "Taco", "Táctil", "Tacto", "Tacha", "Tajo", "Talar", "Talco", "Talento", "Talón", "Talla", "Talle", "Tamiz", "Tanque", "Tanto", "Tapa", "Tapar", "Tapiz",
    "Tapón", "Tardar", "Tarde", "Tarea", "Tarifa", "Tarima", "Tarjeta", "Tarta", "Tartera", "Tasa", "Tasajo", "Tasco", "Tatuar", "Tau", "Tauro", "Taza", "Tazón", "Te", "Teatro", "Techo",
    "Tecla", "Técnico", "Tedio", "Tejado", "Tejar", "Tejer", "Tejido", "Tela", "Telar", "Télex", "Tema", "Temer", "Temor", "Témpano", "Templo", "Temporada", "Temprano", "Tenaz", "Tender", "Tenedor",
    "Tener", "Tenis", "Tenor", "Tensión", "Tenue", "Teoría", "Terapia", "Tercer", "Tercio", "Termal", "Terminal", "Terminar", "Término", "Termo", "Ternero", "Terraza", "Terreno", "Terrible", "Terrón", "Terror",
    "Terso", "Tesoro", "Test", "Testigo", "Teta", "Tetera", "Texto", "Tez", "Ti", "Tía", "Tibia", "Tibio", "Tiburón", "Tie", "Tiempo", "Tienda", "Tiento", "Tierno", "Tierra", "Tiesa",
    "Tieso", "Tiesta", "Tiesto", "Tifón", "Tigre", "Tijera", "Tilde", "Tilo", "Timbal", "Timbrar", "Timbre", "Tímero", "Tímido", "Timo", "Timón", "Tímpano", "Tina", "Tinaja", "Tinte", "Tinto",
    "Tiña", "Tiño", "Tío", "Típico", "Tipo", "Tirar", "Tirón", "Tiro", "Tisana", "Titán", "Títere", "Tiza", "Tiznar", "Tizne", "Toalla", "Tobar", "Tobillo", "Tocado", "Tocar", "Tocina",
    "Todavía", "Todo", "Toga", "Toldo", "Tolerar", "Toma", "Tomar", "Tomate", "Tomillo", "Tomo", "Tonal", "Tonel", "Tonico", "Tono", "Topar", "Tope", "Topo", "Toque", "Tórax", "Torcer",
    "Torcida", "Tordo", "Toreo", "Tormenta", "Torno", "Toro", "Torpe", "Torre", "Tortuga", "Torvo", "Tos", "Tosco", "Toser", "Total", "Tótem", "Tóxico", "Traba", "Trabajo", "Trabajar", "Tracción",
    "Tractor", "Traer", "Tráfico", "Trágico", "Trago", "Traje", "Trama", "Trampa", "Trampolín", "Tramo", "Trance", "Tranco", "Tranquilo", "Trapo", "Tras", "Tratado", "Trauma", "Travesaño", "Traza", "Trecho",
    "Tregua", "Treinta", "Tres", "Triaje", "Tribuna", "Tributo", "Trigal", "Trigo", "Trino", "Trío", "Tripa", "Triste", "Tritón", "Triunfo", "Trofeo", "Trompa", "Trompo", "Tronco", "Trono", "Tropa",
    "Trote", "Trozo", "Truco", "Trueno", "Trufa", "Trunco", "Tú", "Túbal", "Tubar", "Tubo", "Tuerca", "Tugurio", "Tumba", "Tumor", "Tundra", "Túnica", "Tupir", "Turba", "Turbo", "Turismo",
    "Turno", "Turpial", "Tutela", "Tutor", "Tuyo", "Ubicar", "Ubre", "Ucase", "Ufano", "Ujal", "Úlcera", "Último", "Ultra", "Umbral", "Un", "Una", "Unción", "Ungir", "Único", "Unidad",
    "Unir", "Uno", "Untar", "Uña", "Uñero", "Uranio", "Urbano", "Urbe", "Urdido", "Urdir", "Urgente", "Urgir", "Urna", "Urraca", "Usar", "Uso", "Usted", "Usura", "Útero", "Útil",
    "Utopía", "Uva", "Vaca", "Vaciado", "Vaciar", "Vacío", "Vado", "Vagar", "Vago", "Vagón", "Vaina", "Vaino", "Valer", "Valiente", "Valioso", "Valla", "Valle", "Valor", "Vals", "Válvula",
    "Vampiro", "Vanadio", "Vanal", "Vandálico", "Vanguardia", "Vanidad", "Vano", "Vapor", "Vara", "Varar", "Variable", "Variar", "Variz", "Varón", "Vaso", "Vástago", "Vasto", "Vate", "Vatio", "Vedar",
    "Vela", "Velar", "Velatorio", "Velo", "Veloz", "Vena", "Venado", "Venal", "Vencer", "Venda", "Vendar", "Vendaval", "Veneno", "Venerar", "Vengar", "Venial", "Venida", "Venir", "Venta", "Ventana",
    "Ventisca", "Ventura", "Ver", "Verano", "Veraz", "Verbo", "Verdad", "Verde", "Vereda", "Verja", "Vermut", "Verso", "Vertebra", "Vértice", "Vértigo", "Vesícula", "Vespa", "Vestidura", "Vestigio", "Vestir",
    "Veta", "Veto", "Vía", "Viajar", "Viaje", "Vibra", "Vibrar", "Vicio", "Víctima", "Victor", "Victoria", "Vid", "Vida", "Vidrio", "Viejo", "Viento", "Viernes", "Viga", "Vigía", "Vila",
    "Villa", "Villano", "Vinagre", "Vincular", "Vino", "Viña", "Viola", "Víper", "Viraje", "Viral", "Virgen", "Viril", "Virtual", "Virtud", "Virus", "Visaje", "Visión", "Visitar", "Vislumbrar", "Viso",
    "Vista", "Visual", "Vital", "Vitre", "Vitrina", "Xenón", "Yate", "Yelmo", "Yema", "Yeti", "Yodo", "Yoga", "Yogur", "Yunque", "Yute", "Zafiro", "Zaguán", "Zángano", "Zanja", "Zapato", "Zar", "Zarpa", "Zarza", "Zigzag", "Zinc", "Zócalo", "Zodiaco", "Zona", "Zorro", "Zueco", "Zumbido", "Zurdo"
];
